# MIT License
# Copyright (c) 2025 Terry Drymonacos

---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0 # Check for the latest version to ensure the hook detects secrets effectively and includes the latest security updates.
    hooks:
      - id: detect-secrets
  - repo: local # Local repositories do not require a 'rev' field
    hooks:
      - id: pytest
        name: pytests
        entry: pytest backend/tests
        language: system
        types: [python]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: Insert license header for SQL files
        files: \.sql$
        exclude: |
          (?x)
          ^\.github/|
          ^.*/.*_vendor/
        args:
          - --comment-style
          - "/*||*/"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all RST files
        # Exclude RST files in the .github directory, vendor directories, and newsfragments folder
        exclude: ^\.github/.*$|^.*/.*_vendor/|newsfragments/.*\.rst$
        args:
          - --comment-style
          - "||"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
        files: \.rst$
      - id: insert-license
        name: Add license for CSS/JS/JSX/PUML/TS/TSX
        files: \.(css|jsx?|puml|tsx?)$
        exclude: |
          ^\.github/.*$| # Exclude files in the .github directory
          ^.*/.*_vendor/| # Exclude files in vendor directories
          ^airflow/www/static/js/types/api-generated.ts$| # Exclude auto-generated TypeScript files
          ui/openapi-gen/ # Exclude files in the OpenAPI generation directory
        args:
          - --comment-style
          - "/*!| *| */"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all JINJA template files
        files: ^airflow/www/templates/.*\.html$
        exclude: ^\.github/.*$|^.*/.*_vendor/
        args:
          - --comment-style
          - "{#||#}"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all Shell files
        exclude: ^\.github/.*$|^.*/.*_vendor/|^dev/breeze/autocomplete/.*$
        files: \.bash$|\.sh$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all toml files
        exclude: ^\.github/.*$|^.*/.*_vendor/|^dev/breeze/autocomplete/.*$
        files: \.toml$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all Python files
        exclude: ^\.github/.*$|^.*/.*_vendor/
        files: \.py$|\.pyi$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all XML files
        exclude: ^\.github/.*$|^.*/.*_vendor/
        files: \.xml$
        args:
          - --comment-style
          - "<!--||-->"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all Helm template files
        files: ^chart/templates/.*
        args:
          - --comment-style
          - "{{/*||*/}}"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all YAML files except Helm templates
        types: [yaml]
        files: \.ya?ml$
        exclude: >
          # Exclude files in the .github directory
          ^\.github/.*$|
          # Exclude files in vendor directories
          ^.*/.*_vendor/|
          # Exclude Helm template files
          ^chart/templates/.*|
          # Exclude reproducible build YAML file
          .*/reproducible_build.yaml$|
          # Exclude generated OpenAPI YAML file
          ^airflow/api_fastapi/openapi/v1-generated.yaml$|
          # Exclude pnpm-lock YAML file
          ^.*/pnpm-lock.yaml$|
          .*/secret

      - id: insert-license
        name: Add license for all Terraform files
        files: \.tf$
        exclude: >
          .*\.terraform$|
          ^.*/.*_vendor/
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all Markdown files
        files: \.md$
        exclude: PROVIDER_CHANGES.*\.md$|^.*/.*_vendor/
        args:
          - --comment-style
          - "<!--|| -->"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
      - id: insert-license
        name: Add license for all other files
        exclude: ^\.github/.*$|^.*/.*_vendor/
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - ./LICENSE.txt
          - --fuzzy-match-generates-todo
        # Include configuration files commonly used in applications
        files: >
          \.cfg$| # Configuration files
          \.conf$| # Configuration files
          \.ini$| # INI format files
          \.ldif$| # LDAP Data Interchange Format files
          \.properties$| # Java properties files
          \.readthedocs$| # ReadTheDocs configuration files
          \.service$| # Systemd service files
          Dockerfile.*$ # Docker configuration files
