# MIT License
# Copyright (c) 2025 Terry Drymonacos

---
- name: Converge
  hosts: all
  gather_facts: false
  vars_files:
    - "../../../../inventories/dev/group_vars/secrets.yml"
    - "../../../../inventories/dev/group_vars/dev.yml"
  tasks:
    - name: Task being tested # noqa: role-name[path]
      ansible.builtin.import_role:
        name: "../../../packaging"
