# MIT License
# Copyright (c) 2025 Terry Drymonacos

# MIT License


---
driver:
  name: docker
  options:
    requirements_file: requirements.yml
platforms:
  - name: mod1-1
    image: terrdry.01:latest
    build:
      context: "./backend"
      dockerfile: "build-flask.dockerfile"
    pre_build_image: false
  # - name: molecule-flask-container
  #   image: terrdry.01:latest
  #   build:
  #     context: "./backend"
  #     dockerfile: "build-flask.dockerfile"
  #   pre_build_image: true
      # - name: terryd-flask
  #   build:
  #     context: "./backend"
  #     dockerfile: "build-flask.dockerfile"
  #   pre_build_image: true
# services:
#   - name: docker-compose
#     compose:
#       files:
#         - files/docker/docker-compose.yml
#       options:
#         build: true
#         pull: true
