# MIT License
# Copyright (c) 2025 Terry Drymonacos

---

driver:
  name: docker
  options:
    requirements_file: requirements.yml
platforms:
  - name: instance
    image: python:3.11-slim
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - converge
