# MIT License
# Copyright (c) 2025 Terry Drymonacos
---
- name: Converge
  hosts: all
  gather_facts: false
  vars_files:
    - "../../../../inventories/dev/group_vars/secrets.yml"
    - "../../../../inventories/dev/group_vars/dev.yml"

  tasks:

    # This task includes sensitive variables from the specified secrets file.
    # It uses the 'include_vars' module to load variables from
    # '../../inventories/dev/group_vars/secrets.yml' into the current play context.
    # Ensure that the referenced secrets file exists and is secured appropriately,
    # as it may contain confidential information such as passwords or API keys.
    - name: debu
      ansible.builtin.debug:
        var: inventory_dir

    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"
    - name: Debug vpc_cidr
      ansible.builtin.debug:
        var: vpc_cidr
    # This task imports the 'network' role from a relative path.
    # It is used in molecule testing to verify the behavior of the role in isolation.
    # The '#noqa: role-name[path]' comment disables linting for the role path format.
    - name: Task being tested # noqa: role-name[path]
      ansible.builtin.import_role:
        name: "../../../network"
