# MIT License
# Copyright (c) 2025 Terry Drymonacos

all:
  vars:
    python_interpreter_path: /Users/terrydrymonacos/develop/tarot/.venv/bin/python3.13
  children:
    dev:
      hosts:
        localhost:
          ansible_connection: local
          # ansible_python_interpreter: "{{ python_interpreter_path }}"
    qa:
      hosts:
        localhost:
          ansible_connection: local
          # ansible_python_interpreter: "{{ python_interpreter_path }}"
    prod:
      hosts:
        localhost:
          ansible_connection: local
          # ansible_python_interpreter: "{{ python_interpreter_path }}"
