# MIT License
# Copyright (c) 2025 Terry Drymonacos

all:
  children:
    dev:
      hosts:
        localhost:
          ansible_host: 127.0.0.1
          ansible_connection: local
          ansible_python_interpreter: /Users/terrydrymonacos/develop/tarot/.venv/bin/python3.13
        nomad:
          ansible_host: 127.0.0.1
          ansible_connection: local
          ansible_python_interpreter: /Users/terrydrymonacos/develop/tarot/.venv/bin/python3.13
