# MIT License
# Copyright (c) 2025 Terry Drymonacos
---
- name: Display secrets from secrets.yml
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include secrets
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/secrets.yml"

    - name: Debug secret_key_aws
      ansible.builtin.debug:
        msg: "The secret_key_aws is {{ secret_key_aws }}"
      debugger: always

    - name: Debug access_key_aws
      ansible.builtin.debug:
        msg: "The access_key_aws is {{ access_key_aws }}"
      debugger: always
