# MIT License
# Copyright (c) 2025 Terry Drymonacos

---
- name: Display secrets from secrets.yml
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include secrets
      ansible.builtin.include_vars:
        file: /Users/terrydrymonacos/develop/tarot/infrastructure/ansible/inventories/dev/group_vars/secrets.yml

    - name: Debug secret_key_aws
      ansible.builtin.debug:
        msg: "The secret_key_aws is {{ secret_key_aws }}"

    - name: Debug access_key_aws
      ansible.builtin.debug:
        msg: "The access_key_aws is {{ access_key_aws }}"
