
# MIT License
# Copyright (c) 2025 Terry Drymonacos

driver:
  name: vagrant
  provider:
    name: vmware_desktop

platforms:
  - name: nomad
    box: tknerr/ubuntu2004-desktop
    memory: 2048  # Memory allocated to the instance in MB
    # Number of virtual CPUs allocated to the instance
    cpus: 2
provisioner:
  name: ansible
  config_options:
    defaults:
      # library: ${workspaceFolder}:".venv/lib/python3.13/site_packages"
      #library: "{{ lookup('env', 'LIBRARY_PATH') }}"
      library: "{{ lookup('env', 'LIBRARY_PATH') }}"
      # Dynamically sets the library path from the environment variable `LIBRARY_PATH`
      # library: "{{ lookup('env', 'LIBRARY_PATH') }}"
