# MIT License
# Copyright (c) 2025 Terry Drymonacos

- name: Debug
  ansible.builtin.debug:
    msg: "{{ role_path }}"


- name: Create Terraform var file from template
  ansible.builtin.template:
    src: terraform_vars.json.j2
    dest: "{{ role_path }}/files/terraform/terraform_vars.json"

# - name: Run Terraform Init
#   ansible.builtin.command: terraform init
#   args:
#     chdir: "{{ role_path }}/files/terraform"

# - name: Run Terraform Apply with vars
#   ansible.builtin.command: terraform apply -auto-approve -var-file="terraform_vars.json"
#   args:
#     chdir: "{{ role_path }}/files/terraform"

# - name: Get Terraform outputs as JSON
#   ansible.builtin.command: terraform output -json
#   register: tf_output
#   args:
#     chdir: "{{ role_path }}/files/terraform"

# - name: Set outputs as Ansible facts
#   ansible.builtin.set_fact:
#     tf_outputs: "{{ tf_output.stdout | from_json }}"

# - name: Debug VPC ID
#   ansible.builtin.debug:
#     msg: "The created VPC ID is {{ tf_outputs.vpc_id.value }}"
