# Write your playbook below.
# Replace these contents with the tasks you'd like to complete and the modules you need.
# For help getting started, check out https://www.redhat.com/en/topics/automation/what-is-an-ansible-playbook
---
# This playbook installs the latest version of Ansible and its collections.
# It is designed to be run on localhost and does not gather facts.


- name: Setup Ansible and required collections
  hosts: localhost
  gather_facts: false


  tasks:
    - name: Ensure version of Ansible is installed
      ansible.builtin.pip:
        name: ansible
        version: 2.18.5

    - name: Install version of Ansible
      ansible.builtin.pip:
        name: ansible
        version: 2.18.5

    - name: Install version of Ansible collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install --upgrade community.general
      args:
        creates: ~/.ansible/collections/ansible_collections/community/general
