Vagrant.configure("2") do |config|
    config.vm.box = "tknerr/ubuntu2004-desktop"
    config.vm.box_version = "23.1027.1"
    config.vm.box_check_update = false
    config.vm.synced_folder "output/", "/home/vagrant", owner: "vagrant"
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook= "provisioning/playbook.yaml"

    end

    config.vm.provider "vmware_desktop" do |vmware|
        vmware.gui = false
        vmware.allowlist_verified = true
        vmware.memory = "2048"
        vmware.cpus = 2
    end
    config.vm.network "forwarded_port", guest: 5000, host: 5033
end
